# This "test" on Circle will always fail :)

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-

      - run:
          name: Always fail
          command: |
            exit 1;          
